package tuenti.contest.challenge19;

import java.util.Scanner;

import org.apache.log4j.Logger;

import tuenti.contest.Freqs;

public class Challenge19 {
	private static Logger log = Logger.getLogger(Challenge19.class);

	public static void main(String[] args) throws InterruptedException {
		Challenge19 main = new Challenge19();
		try {
			main.process();
		} catch (Exception e) {
			log.error("Exception:", e);
			Thread.sleep(600000);
		}
	}

	private String testString = "YmM3OWYxMDNiYzc5ZjEwMWJjNzlmMGZjYmM3OWYwZmJiYzc5ZjBlYWJjNzlmMGY3YmM3OWYxMGFiYzc5ZjEwNWJjNzlmMTAxYmM3OWYxMTBiYzc5ZjEyMGJjNzlmMTMwYmM3OWYxM2ViYzc5ZjEzY2JjNzlmMTI5YmM3OWYxMTliYzc5ZjExMWJjNzlmMTI0YmM3OWYxMTRiYzc5ZjExY2JjNzlmMTFkYmM3OWYxMjRiYzc5ZjEyMWJjNzlmMTFlYmM3OWYxMWJiYzc5ZjExNGJjNzlmMTFhYmM3OWYxMDliYzc5ZjExM2JjNzlmMTE2YmM3OWYxMDJiYzc5ZjEwOGJjNzlmMTE1YmM3OWYxMDViYzc5ZjBmYWJjNzlmMTA5YmM3OWYxMTZiYzc5ZjEyMWJjNzlmMTMwYmM3OWYxNDJiYzc5ZjEzY2JjNzlmMTNhYmM3OWYxNDZiYzc5ZjEzMmJjNzlmMTI2YmM3OWYxMjViYzc5ZjEyMmJjNzlmMTEwYmM3OWYxMWJiYzc5ZjExNGJjNzlmMTBkYmM3OWYxMTFiYzc5ZjEwZWJjNzlmMTEwYmM3OWYwZmViYzc5ZjBlY2JjNzlmMGQ5YmM3OWYwZDRiYzc5ZjBlMWJjNzlmMGRiYmM3OWYwZTRiYzc5ZjBlYmJjNzlmMGRlYmM3OWYwZTRiYzc5ZjBlN2JjNzlmMGYyYmM3OWYwZGViYzc5ZjBjYmJjNzlmMGNkYmM3OWYwY2NiYzc5ZjBiZWJjNzlmMGM1YmM3OWYwYzViYzc5ZjBjNWJjNzlmMGI1YmM3OWYwYjhiYzc5ZjBhZmJjNzlmMGJlYmM3OWYwYmRiYzc5ZjBjNWJjNzlmMGM1YmM3OWYwZDliYzc5ZjBkMGJjNzlmMGRkYmM3OWYwZGFiYzc5ZjBkM2JjNzlmMGUxYmM3OWYwZTBiYzc5ZjBlM2JjNzlmMGUzYmM3OWYwZDJiYzc5ZjBkYmJjNzlmMGVlYmM3OWYwZGNiYzc5ZjBkYmJjNzlmMGNkYmM3OWYwZDNiYzc5ZjBlN2JjNzlmMGY4YmM3OWYwZmRiYzc5ZjBmZmJjNzlmMGY1YmM3OWYxMDNiYzc5ZjBmOWJjNzlmMGYzYmM3OWYwZjZiYzc5ZjBlNWJjNzlmMGU2YmM3OWYwZjJiYzc5ZjBlZWJjNzlmMGVlYmM3OWYwZjNiYzc5ZjBmMmJjNzlmMTAxYmM3OWYxMDdiYzc5ZjBmZmJjNzlmMGYzYmM3OWYwZjViYzc5ZjBlN2JjNzlmMGY4YmM3OWYxMGFiYzc5ZjExN2JjNzlmMTIxYmM3OWYxMzFiYzc5ZjEyYmJjNzlmMTNmYmM3OWYxNGFiYzc5ZjE0ZWJjNzlmMTVjYmM3OWYxNTZiYzc5ZjE0NWJjNzlmMTRiYmM3OWYxNDRiYzc5ZjE1OGJjNzlmMTQ2YmM3OWYxNGViYzc5ZjE0MmJjNzlmMTNkYmM3OWYxMzBiYzc5ZjEyMWJjNzlmMTFkYmM3OWYxMTNiYzc5ZjEwNGJjNzlmMTAzYmM3OWYxMTJiYzc5ZjEwOWJjNzlmMTBmYmM3OWYwZmNiYzc5ZjBlZmJjNzlmMGYwYmM3OWYwZjJiYzc5ZjBlZmJjNzlmMGVjYmM3OWYwZWRiYzc5ZjBlMGJjNzlmMGUzYmM3OWYwZjViYzc5ZjBmZWJjNzlmMGZlYmM3OWYxMGRiYzc5ZjBmZWJjNzlmMGYxYmM3OWYwZjZiYzc5ZjBmNmJjNzlmMTAxYmM3OWYxMDBiYzc5ZjBmM2JjNzlmMGY0YmM3OWYxMDJiYzc5ZjBmN2JjNzlmMTA4YmM3OWYxMDhiYzc5ZjExMWJjNzlmMGZmYmM3OWYwZmFiYzc5ZjBlZGJjNzlmMGYwYmM3OWYxMDRiYzc5ZjBmY2JjNzlmMTBkYmM3OWYwZmJiYzc5ZjEwNWJjNzlmMGY2YmM3OWYwZjRiYzc5ZjEwMWJjNzlmMTAyYmM3OWYxMDdiYzc5ZjExOWJjNzlmMTJkYmM3OWYxMWRiYzc5ZjExM2JjNzlmMTBkYmM3OWYxMGZiYzc5ZjBmZGJjNzlmMGVmYmM3OWYwZTFiYzc5ZjBkYWJjNzlmMGNiYmM3OWYwY2NiYzc5ZjBkNGJjNzlmMGM0YmM3OWYwYjdiYzc5ZjBiNWJjNzlmMGM4YmM3OWYwYzNiYzc5ZjBkNGJjNzlmMGMxYmM3OWYwYjJiYzc5ZjBiMWJjNzlmMGE1YmM3OWYwYjBiYzc5ZjBhNWJjNzlmMGFmYmM3OWYwOWRiYzc5ZjBhNGJjNzlmMDkyYmM3OWYwOWViYzc5ZjBhM2JjNzlmMDhmYmM3OWYwODZiYzc5ZjA3YWJjNzlmMDgzYmM3OWYwOTZiYzc5ZjBhNmJjNzlmMGExYmM3OWYwYTJiYzc5ZjA5NWJjNzlmMDllYmM3OWYwOGZiYzc5ZjA4ZmJjNzlmMDhkYmM3OWYwODliYzc5ZjA3Y2JjNzlmMDc1";
	private String testResult = "ZGUzY2Y4ODFiY2RiZmJjNzlmMGVhMzc3OGYzZTIxNGRiODdlZjFlN2M0ODM3OGYzZTI2MDczZGJjNzlmMTI5NDE4ZGUzY2Y4OTIyMDQwMjNiYWViYWM4ZGJjNzlmMTA5MjgzZGUzY2Y4ODEwYzZhMGE5ZTY5NjdlZjFlN2M1MDlhNzhjZGUzY2Y4OTkyOGZiYmJjNzlmMTEwMmQ5NjQ0NzQyZGUzY2Y4N2Y2ZjFlN2MzYjM3OGYzZTFiMmQ5YWQxMjNhNjMwNjVlZjFlN2MzN2I3OGYzZTE5NjEzZTkwZTAwMDgwNmI5ZWY5MDA2ZjFlN2MzNjU3MzVkNjRlN2MzMDM3OGYzZTFhNDRlZjFlN2MzYmI3OGYzZTFiOGZhNDM2ZjFlN2MzOWY3OGYzZTFmMDI4NGIxY2IzNDFlZjFlN2MzOTQxMzFjMDA1N2NmMTk4NTAyNGI3OGYzZTFmMWJjNzlmMTBhMzRhZGUzY2Y4OThiNWJjNzlmMTNmMmM0MzlhZGUzY2Y4YTI4Y2NlZjFlN2M1NjM3OGYzZTI4YzQyOGRhNjhiOGIyMmY5ZWI4ZGJjNzlmMGZjNGMxMDlkNzQxNGMzZGUzY2Y4N2E5MjAxZThhNjI4MDViZTk4MjcyYmJjNzlmMTA4MDA5ZGUzY2Y4N2ZiNjk4N2JjNzlmMTA0NjM3OGYzZTIxYmJjNzlmMGZiMjkxNzhkMDQ1ZGUzY2Y4OGNlZjFlN2M0YjUwNTlhMGI3OGYzZTFmYTkyNGNhMjA5MDgyNmY2ZjFlN2MzMjFiZGUzY2Y4NmE2ZjFlN2MzMDUxN2Q0MmQ1MmI3OGYzZTEzYTNlZjFlN2MyNDhjMTc3OGYzZTExZWJhODRlZjFlN2MyNWI3OGYzZTE0Y2Q4Mjk5Mjg4MGYzODliMg";
	private String testString2 = "NTRlODdmYTU1NGU4N2ZhMDU0ZTg3ZmE2NTRlODdmYjI1NGU4N2ZjNTU0ZTg3ZmM3NTRlODdmYzY1NGU4N2ZiYTU0ZTg3ZmM0NTRlODdmZDY1NGU4N2ZkZTU0ZTg3ZmU0NTRlODdmZTk1NGU4N2ZmMDU0ZTg3ZmYxNTRlODdmZGU1NGU4N2ZkZTU0ZTg3ZmRkNTRlODdmZDU1NGU4N2ZlMDU0ZTg3ZmU3NTRlODdmZWE1NGU4N2ZkNzU0ZTg3ZmVhNTRlODdmZGY1NGU4N2ZkOTU0ZTg3ZmRmNTRlODdmZDk1NGU4N2ZkMDU0ZTg3ZmRiNTRlODdmZTk1NGU4N2ZlNzU0ZTg3ZmUzNTRlODdmZWQ1NGU4N2ZmYzU0ZTg4MDA0NTRlODgwMGI1NGU4ODAwNzU0ZTg4MDE1NTRlODgwMGI1NGU4ODAxZjU0ZTg4MDFjNTRlODgwMmE1NGU4ODAyNjU0ZTg4MDMxNTRlODgwNDI1NGU4ODAzYzU0ZTg4MDJmNTRlODgwMmE1NGU4ODAyODU0ZTg4MDM2NTRlODgwNDE1NGU4ODAzYjU0ZTg4MDMxNTRlODgwMjI1NGU4ODAwZTU0ZTg4MDE2NTRlODgwMjE1NGU4ODAyYzU0ZTg4MDJjNTRlODgwMWE1NGU4ODAwYzU0ZTg4MDE0NTRlODgwMjM1NGU4ODAyMjU0ZTg4MDJkNTRlODgwMzE1NGU4ODAxZDU0ZTg4MDFmNTRlODgwMTI1NGU4ODAwYjU0ZTg4MDFiNTRlODgwMmU1NGU4ODAzMTU0ZTg4MDI5NTRlODgwM2Q1NGU4ODAzNTU0ZTg4MDQxNTRlODgwNGY1NGU4ODA0MjU0ZTg4MDM4NTRlODgwMmE1NGU4ODAzNjU0ZTg4MDJjNTRlODgwNDA1NGU4ODAzYTU0ZTg4MDI5NTRlODgwMjk1NGU4ODAzNTU0ZTg4MDQ4NTRlODgwNTc1NGU4ODA2MjU0ZTg4MDc1NTRlODgwNzc1NGU4ODA4YTU0ZTg4MDg0NTRlODgwOGQ1NGU4ODA4OTU0ZTg4MDk3NTRlODgwODU1NGU4ODA5NzU0ZTg4MDg4NTRlODgwODI1NGU4ODA3NzU0ZTg4MDczNTRlODgwN2I1NGU4ODA2ZDU0ZTg4MDZkNTRlODgwN2Y1NGU4ODA4OTU0ZTg4MDkwNTRlODgwOGQ1NGU4ODA5ZDU0ZTg4MGE4NTRlODgwYTc1NGU4ODBiYTU0ZTg4MGMwNTRlODgwYzg1NGU4ODBkYjU0ZTg4MGQ4NTRlODgwZGM1NGU4ODBlMzU0ZTg4MGQzNTRlODgwYzA1NGU4ODBjNzU0ZTg4MGRiNTRlODgwZTI1NGU4ODBkNjU0ZTg4MGQwNTRlODgwY2I1NGU4ODBkNjU0ZTg4MGUyNTRlODgwZGM1NGU4ODBlYTU0ZTg4MGZjNTRlODgwZWQ1NGU4ODBlZjU0ZTg4MGY1NTRlODgwZWI1NGU4ODBmZjU0ZTg4MGYzNTRlODgwZWM1NGU4ODBmZDU0ZTg4MTBkNTRlODgxMDc1NGU4ODBmNjU0ZTg4MGZmNTRlODgxMDY1NGU4ODEwMzU0ZTg4MGYwNTRlODgwZWQ1NGU4ODBmNzU0ZTg4MTA2NTRlODgwZmQ1NGU4ODEwOTU0ZTg4MTE4NTRlODgxMWE1NGU4ODEwYjU0ZTg4MTA0NTRlODgwZjQ1NGU4ODBmYTU0ZTg4MTBkNTRlODgxMWY1NGU4ODEyODU0ZTg4MTI5NTRlODgxMmE1NGU4ODEyOTU0ZTg4MTM1NTRlODgxMjY1NGU4ODEyOTU0ZTg4MTFjNTRlODgxMGY1NGU4ODEyMzU0ZTg4MTM1NTRlODgxNDU1NGU4ODEzMjU0ZTg4MTM5NTRlODgxM2Q1NGU4ODE0YzU0ZTg4MTVhNTRlODgxNjg1NGU4ODE2YzU0ZTg4MTYzNTRlODgxNTM1NGU4ODE0ZjU0ZTg4MTQ2NTRlODgxNTE1NGU4ODE1YTU0ZTg4MTRhNTRlODgxNTA1NGU4ODE1ZTU0ZTg4MTYzNTRlODgxNjk1NGU4ODE1YzU0ZTg4MTVlNTRlODgxNTA1NGU4ODE1OTU0ZTg4MTYyNTRlODgxNjQ1NGU4ODE2MTU0ZTg4MTU3NTRlODgxNjA1NGU4ODE1NDU0ZTg4MTVjNTRlODgxNjk1NGU4ODE1NTU0ZTg4MTRhNTRlODgxNWI1NGU4ODE2ZjU0ZTg4MTczNTRlODgxNzk1NGU4ODE3ZDU0ZTg4MTc1NTRlODgxNzc1NGU4ODE3NzU0ZTg4MTZhNTRlODgxNmM1NGU4ODE4MDU0ZTg4MThmNTRlODgxODA1NGU4ODE4NjU0ZTg4MTg5NTRlODgxNzk1NGU4ODE4NzU0ZTg4MTg1NTRlODgxN2Q1NGU4ODE4YjU0ZTg4MTg3NTRlODgxNzU1NGU4ODE2YjU0ZTg4MTZhNTRlODgxNTg1NGU4ODE1ODU0ZTg4MTY4";
	private void process() {
		Scanner in = new Scanner(System.in);
		//String line = in.nextLine();
		System.out.println(testString.length());
		String parsedTest = removeGarbage2(testString);
//		parsedTest = rot13(parsedTest);
		System.out.println(parsedTest.length());
		for (int i = 0; i < parsedTest.length(); i = i+74) {
			System.out.println(parsedTest.substring(i, i+74));
		}
		System.out.println(testResult.length());
		for (int i = 0; i < testResult.length(); i = i+35) {
			System.out.println(testResult.substring(i, i+35));
		}
//		freqs = new Freqs(testResult);
//		freqs.countChars();
//		freqs.printTable();
//		System.out.println(testString2.length());
		parsedTest = removeGarbage2(testString2);
		System.out.println(parsedTest.length());
//		for (int i = 0; i < parsedTest.length(); i = i+11) {
//			System.out.println(parsedTest.substring(i, i+11));
//		}
//		freqs = new Freqs(parsedTest);
//		freqs.countChars();
//		freqs.printTable();
		
		//LZ77v01 compressor = new LZ77v01();
		//compressor.doIt(line);
	}
	
	private String removeGarbage(String text) {
		String result = "";
		for (int i= 0; i<text.length()/32;i++) {
			int ofset = i*32;
			result += text.substring(ofset+7, ofset+11);
			result += text.substring(ofset+18, ofset+22);
			result += text.substring(ofset+29, ofset+32);
		}
		return result;
	}

	private String removeGarbage2(String text) {
		String result = "";
		for (int i= 0; i<text.length();i++) {
			if (Character.isLowerCase(text.charAt(i))) {
				result += text.charAt(i);
			}
		}
		return result;
	}
	private String rot13(String s) {
		String result = "";
	    for (int i = 0; i < s.length(); i++) {
	        char c = s.charAt(i);
	        if       (c >= 'a' && c <= 'm') c += 13;
	        else if  (c >= 'n' && c <= 'z') c -= 13;
	        else if  (c >= 'A' && c <= 'M') c += 13;
	        else if  (c >= 'A' && c <= 'Z') c -= 13;
	        result +=c;
	    }
	    return result;
	}
	
}
